option('tests', type: 'feature', value: 'auto', description: 'enable building the test executable')
option('examples', type: 'feature', value: 'auto', description: 'enable building the examples')
option('sim', type: 'feature', value: 'auto', description: 'enable simulation')
option('docs', type: 'boolean', value: false, description: 'set to true to build documentation')
option('cli-term', type: 'feature', value: 'auto', description: 'set to true to build cli-term')
option('led-example', type: 'feature', value: 'disabled', description: 'set to true to build cli-term')
option('embedded', type: 'boolean', value: false, description: 'set to true if cli is used to build an embedded target')
