name: testing 
on: [push]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
    - uses: BSFishy/meson-build@v1.0.3
      with:
        action: test
        setup-options: -Dauto_features=disabled -Dtests=enabled
        meson-version: 1.1.0
